# Algorand: MainNet
algorand:
    live:
        libcore:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core.git
            branch: int-algorand-libcorev1
        bindings:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core-node-bindings.git
            branch: int-algorand
            #commit: f1c37acae02932510c711c23d60ef28d72315464
        live_common:
            repository: git@github.com:Ledger-Coin-Integration-team/ledger-live-common.git
            branch: algorand
        live_desktop:
            repository: git@github.com:LFBarreto/ledger-live-desktop.git
            branch: LL-2719

# Algorand: TestNet
algorand_test:
    live:
        libcore:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core.git
            branch: int-algorand-libcorev1
        bindings:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core-node-bindings.git
            branch: int-algorand
        live_common:
            repository: git@github.com:Ledger-Coin-Integration-team/ledger-live-common.git
            branch: algorand
        live-desktop:
            repository: git@github.com:LFBarreto/ledger-live-desktop.git
            branch: LL-2719
        options:
            - API_ALGORAND_BLOCKCHAIN_EXPLORER_API_ENDPOINT=https://testnet-algorand.api.purestake.io

# Algorand: development of the tests performed by the bot
algorand_bot_dev:
    live:
        libcore:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core.git
            branch: int-algorand-libcorev1
        bindings:
            repository: git@github.com:Ledger-Coin-Integration-team/lib-ledger-core-node-bindings.git
            branch: int-algorand
        live_common:
            repository: git@github.com:glethuillier/ledger-live-common.git
            branch: algorand
        options:
            - API_ALGORAND_BLOCKCHAIN_EXPLORER_API_ENDPOINT=https://testnet-algorand.api.purestake.io

stellar:
    vault:
        libcore:
            repository: git@github.com:LedgerHQ/lib-ledger-core.git
            branch: develop
            commit: 78a3b0f08e5e5adfa0a9220128e5c27d8feadabb
        wallet_daemon:
            repository: git@github.com:Ledger-Coin-Integration-team/ledger-wallet-daemon.git
            branch: COIN-435-stellar-integration
        vault_integration:
            repository: git@github.com:noirbizarre/vault-integration.git
            branch: all-in-one
        vault_front:
            repository: git@github.com:LedgerHQ/ledger-vault-front.git
            branch: coin/stellar


tezos:
    vault:
        libcore:
            repository: git@github.com:LedgerHQ/lib-ledger-core.git
            branch: master
        wallet_daemon:
            repository: git@github.com:LedgerHQ/ledger-wallet-daemon.git
            branch: coin/tezos
        vault_integration:
            repository: git@github.com:noirbizarre/vault-integration.git
            branch: all-in-one
        vault_front:
            repository: git@github.com:LedgerHQ/ledger-vault-front.git
            branch: coin/tezos